#! /bin/sh

set -eu

ONTOLOGY_VERSION=${ONTOLOGY_VERSION:-1.0.1}
ONTOLOGY_DARWIN_SHA=${ONTOLOGY_DARWIN_SHA:-a68390591e93be008a09f36841eb617049b7f5a06977f0e1b4d3cefc72646196}
ONTOLOGY_LINUX_SHA=${ONTOLOGY_LINUX_SHA:-0eab09230bfcb2f14d0917caff26973928b51affdaa8c0e63a3a36d97985ab86}

if [ "$(uname -s)" = "Darwin" ]; then
  OS=darwin
  SHA="$ONTOLOGY_DARWIN_SHA"
else OS=linux 
  OS=linux
  SHA="$ONTOLOGY_LINUX_SHA"
fi

tmp=$(mkdir ontio)
filename="ontology-${OS}-amd64"
(
  cd "$tmp"

  echo "Downloading ${filename}..."


  curl -sLO "https://github.com/ontio/ontology/releases/download/v${ONTOLOGY_VERSION}/${filename}"

  checksum=$(openssl dgst -sha256 "${filename}" | awk '{ print $2 }')
  if [ "$checksum" != "$SHA" ]; then
    echo "Checksum validation failed." >&2
    exit 1
  fi
)
(
  mv "${filename}"   "ontio"
  cd "ontio"
  mv "${filename}" ontology
  chmod +x ontology  
)

echo "ontology was successfully download 🎉"
echo ""
echo "Visit https://github.com/ontio/ontology/releases for more information."
